# **Ejercicio 1**

In [ ]:
#Mediante ciclos
matrix = []
num = 1

for i in range(8):
    row = []
    for j in range(8):
        row.append(num)
        num += 1
    matrix.append(row)

for row in matrix:
    print(row)

In [2]:
#Forma corta
import numpy as np

A = np.array(range(1,65)).reshape(8,8)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

# **Ejercicio 2**

In [5]:
# Transponiendo la matriz A
A2 = A.T
A2

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [20]:
#Alternativa
M = np.array(range(1,65)).reshape(8,8, order = 'F')
M

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [36]:
#Segunda parte
for i in range(8):
    for j in range(8):
        if '3' in str(M[i][j]):
            M[i][j] = -99
M

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

# Ejercicio **3**

In [120]:
# Creando la matriz B 
B = np.array(np.arange(0.4,0.8,0.01)).reshape(8,5)
B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

In [121]:
# Concatenar las matrices
N = np.concatenate((M,B), axis = 1)
N.shape

(8, 13)

In [122]:
np.mean(N, axis=0)

array([ -8.25 ,  -1.5  ,   5.25 , -20.25 , -81.625,  26.75 ,  33.5  ,
        40.25 ,   0.575,   0.585,   0.595,   0.605,   0.615])

In [123]:
# Parte tres del ejercicio
Z = np.append(N,[np.mean(N, axis=0)], axis= 0)
Z.shape

(9, 13)

In [124]:
Z

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ],
       [  8.   ,  16.   ,  24.   , -99.   ,  40.   ,  48.   , 

In [127]:
# Parte 4. Agregar una columna al final con el valor maximo de cada fila
F = np.max(Z, axis=1)
data = np.concatenate((Z,F[:,None]), axis = 1)
print(data.shape)

# Parte 5. Guardar el archivo 
np.savetxt('datos.txt', data, delimiter=',', fmt='%.3f')

(9, 14)


In [128]:
# Lectura de los datos
data_read = np.loadtxt("datos.txt", delimiter=",")
data_read

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],